#ifndef _BRUNODEA__CG_T1_MACROS_H_
#define _BRUNODEA__CG_T1_MACROS_H_

#define MY_PI 3.14159265

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define SAMPLE_SPINNER_MAX_VALUE 255
#define SAMPLE_SPINNER_MIN_VALUE 0
#define SAMPLE_SPINNER_WIDTH 50

#define BOTTOM_SIDEBAR_HEIGHT (WINDOW_HEIGHT / 5)

#define DCTVIEWER brunodea::DCTViewer::instance()

#define GRAPH_POINT_WIDTH 3
#define GRAPH_POINT_HEIGHT GRAPH_POINT_WIDTH

#endif